import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { OrganizationProvider } from "../src/context/OrganizationContext"; // Add this
import { UserProvider } from "../src/context/UserContext";
import ClientLayout from "./clientlayout";
import { LayoutProvider } from "@/src/context/LayoutContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Piecify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OrganizationProvider>
          <UserProvider>
            <LayoutProvider>
              <ClientLayout>{children}</ClientLayout>
            </LayoutProvider>
          </UserProvider>
        </OrganizationProvider>
      </body>
    </html>
  );
}
